   client:
       container_name: client
       image: openethereum/openethereum:v3.2.6
       user: root
       working_dir: /home/openethereum'

       ports:
       - 8080:8080
       - 8180:8180
       - 8545:8545
       - 30303:30303
       volumes:
       - ./deployment/chain/spec.json:/home/openethereum/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/openethereum/reserved_peers:ro
       - ./deployment/client/password:/home/openethereum/password:ro
       - ./deployment/client/client.toml:/home/openethereum/client.toml:ro
       - ./deployment/client/${NETWORK_NAME}:/home/openethereum/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/openethereum/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/NODE_NAME/key.priv:/home/openethereum/data/network/key
       - ./data/client:/home/openethereum/data
       command: --chain CHAIN_NAME -d /home/openethereum/data
