[parity]
chain = "/home/openethereum/chain.json"

[account]
password = ["/home/openethereum/password"]

[network]
reserved_peers = "/home/openethereum/reserved_peers"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "openethereum", "traces", "rpc", "personal", "openethereum_accounts", "signer", "openethereum_set"]

[mining]
reseal_on_txs = "none"
engine_signer = "ENGINE_SIGNER"

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["http://127.0.0.1:8180"]
apis = ["web3", "eth", "net", "openethereum", "traces", "rpc", "secretstore"]
hosts = ["all"]
