   NODE_NAME:
       container_name: NODE_NAME 
       image: openethereum/openethereum:latest 
       volumes:
       - ./deployment/NODE_NAME.toml:/home/openethereum/config.toml:ro
       - ./deployment/spec.json:/home/openethereum/spec.json:ro
       - ./deployment/reserved_peers:/home/openethereum/reserved_peers
       - ./customchain/config/password:/home/openethereum/password:ro
       - ./customchain/config/keys:/home/openethereum/data/keys/openethereum
       - ./data/NODE_NAME:/home/openethereum/data
       command: --chain /home/openethereum/spec.json --reserved-peers /home/openethereum/reserved_peers --config /home/openethereum/config.toml -d /home/openethereum/data
